/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./../layout/components/AppMain.vue')['default']
    Breadcrumb: typeof import('./../components/Breadcrumb/index.vue')['default']
    CardDrag: typeof import('./../components/CardDrag/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Hamburger: typeof import('./../components/Hamburger/index.vue')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    Link: typeof import('./../layout/components/Sidebar/Link.vue')['default']
    Logo: typeof import('./../layout/components/Sidebar/Logo.vue')['default']
    MyCardDrag: typeof import('./../components/MyCardDrag/index.vue')['default']
    Navbar: typeof import('./../layout/components/Navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screenfull: typeof import('./../layout/components/Navbar/Screenfull.vue')['default']
    Search: typeof import('./../layout/components/Navbar/Search.vue')['default']
    Sidebar: typeof import('./../layout/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./../layout/components/Sidebar/SidebarItem.vue')['default']
    SidebarItemTitle: typeof import('./../layout/components/Sidebar/SidebarItemTitle.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TagsView: typeof import('./../layout/components/TagsView/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
